### ISSUE TITLE
Found 3 issues when there are non-existent Items in the VCXProj.

### ISSUE THREAD

**Issue by genbtc** [algorys/cmakeconverter#3]
1. PreprocessorDefinitions,(under Globals) if this is missing index [0] does not exist. Check for that.

```
INFO : CMakeLists will be build in current directory.
INFO : No Output Debug define.
INFO : No Output Release define.
Traceback (most recent call last):
  File "C:\Software\cmakeconverter-master\cmakeconverter.py", line 84, in <module>
    parse_argument()
  File "C:\Software\cmakeconverter-master\cmakeconverter.py", line 81, in parse_argument
    all_data.create_data()
  File "C:\Software\cmakeconverter-master\convertdata.py", line 27, in create_data
    macros.write_macro(self.data)
  File "C:\Software\cmakeconverter-master\macro.py", line 13, in write_macro
    preprocessor = tree.xpath('//ns:PreprocessorDefinitions', namespaces=ns)[0]
IndexError: list index out of range
```

2.  If PreprocessorDefinitions Exists, but the xml tag is blank, you get this because it can't split whats blank. Check for that.

```
C:\Software\cmakeconverter-master>python "C:\Software\cmakeconverter-master\cmakeconverter.py" -p "C:\UDefrag\ultradefrag-src\src\minimal_vc15\minimal_vc15.vcxproj"
INFO : Project to convert = C:\UDefrag\ultradefrag-src\src\minimal_vc15\minimal_vc15.vcxproj
INFO : CMakeLists will be build in current directory.
INFO : No Output Debug define.
INFO : No Output Release define.
Traceback (most recent call last):
  File "C:\Software\cmakeconverter-master\cmakeconverter.py", line 84, in <module>
    parse_argument()
  File "C:\Software\cmakeconverter-master\cmakeconverter.py", line 81, in parse_argument
    all_data.create_data()
  File "C:\Software\cmakeconverter-master\convertdata.py", line 27, in create_data
    macros.write_macro(self.data)
  File "C:\Software\cmakeconverter-master\macro.py", line 16, in write_macro
    for preproc in preprocessor.text.split(";"):
AttributeError: 'NoneType' object has no attribute 'split'
```
3. RootNamespace under Globals. **Check gracefully and emit a warning/error message.**

```
C:\Software\cmakeconverter-master>python "C:\Software\cmakeconverter-master\cmakeconverter.py" -p "C:\UDefrag\ultradefrag-src\src\wxgui\wxgui.vcxproj"
INFO : Project to convert = C:\UDefrag\ultradefrag-src\src\wxgui\wxgui.vcxproj
INFO : CMakeLists will be build in current directory.
Traceback (most recent call last):
  File "C:\Software\cmakeconverter-master\cmakeconverter.py", line 84, in <module>
    parse_argument()
  File "C:\Software\cmakeconverter-master\cmakeconverter.py", line 81, in parse_argument
    all_data.create_data()
  File "C:\Software\cmakeconverter-master\convertdata.py", line 19, in create_data
    variables.define_variable()
  File "C:\Software\cmakeconverter-master\projectvariables.py", line 59, in define_variable
    projectname = self.tree.xpath('//ns:RootNamespace', namespaces=self.ns)[0]
IndexError: list index out of range
```

**Comment by algorys** [comment]
Hey @genbtc.

I did not know that someone was using this script :wink: , I'll have a look ASAP.

**Comment by algorys** [comment]
@genbtc Fixed.
