### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80

### ISSUE THREAD

**Issue by kegao1** [algorys/cmakeconverter#50]
When using cmake-converter on Linux (Redhat 7) under Anaconda 3, the following error has been generated:

_Traceback (most recent call last):
  File "***/anaconda3/bin/cmake-converter", line 11, in <module>
    sys.exit(main())
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/main.py", line 152, in main
    convert_solution(initial_context, os.path.abspath(args.solution))
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/solution.py", line 296, in convert_solution
    results.append(run_conversion(threads_data))
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/solution.py", line 46, in run_conversion
    project_data['subdirectory'],
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/solution.py", line 199, in convert_project
    data_converter.convert(context)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/data_converter.py", line 124, in convert
    self.collect_data(context)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/data_converter.py", line 48, in collect_data
    context.parser.parse(context)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/vfproj/parser.py", line 153, in parse
    self._parse_nodes(context, root)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/parser.py", line 75, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/vfproj/parser.py", line 245, in __parse_files
    self._parse_nodes(context, filter_node)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/parser.py", line 75, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/vfproj/parser.py", line 263, in __parse_filter
    self._parse_nodes(context, filter_node)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/parser.py", line 69, in _parse_nodes
    self._parse_attributes(context, child_node)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/parser.py", line 89, in_arse_attributes
    attributes_handlers[node_key](context, attr, node.get(attr), node)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/vfproj/parser.py", line 257, in __parse_file_relative_path
    source_group
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/project_files.py", line 102, in add_file_from_node
    self.file_lists_for_include_paths)
  File "***/anaconda3/lib/python3.6/site-packages/cmake_converter/visual_studio/vfproj/project_files.py", line 39, in include_directive_case_check
    file_text = file.read()
  File "***/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 10472: ordinal not in range(128)_

after changing the Line 38 in cmake_converter/visual_studio/vfproject/project_files.py from "file = open(file_abs_path, 'r')" to "file = open(file_abs_path, 'r', errors="ignore")", the error is gone. I'm not sure if this causes other problems. 

On Windows, it doesn't have this error.

**Comment by pavelliavonau** [comment]
Can you provide solution example to reproduce error?

**Comment by pavelliavonau** [comment]
No response.
