### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by zowers** [algorys/cmakeconverter#52]
convertion fails with AttributeError

0.284577 101> INFO : Debug|Win32 : GenerateDebugInformation is {'ln_flags': '/DEBUG'} 
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/visual_studio/solution.py", line 43, in run_conversion
    project_data['subdirectory'],
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/visual_studio/solution.py", line 207, in convert_project
    data_converter.convert(context)
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/data_converter.py", line 123, in convert
    self.collect_data(context)
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/data_converter.py", line 49, in collect_data
    context.parser.parse(context)
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/visual_studio/vcxproj/parser.py", line 113, in parse
    self._parse_nodes(context, root)
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/parser.py", line 75, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/visual_studio/vcxproj/parser.py", line 155, in __parse_item_definition_group
    self._parse_nodes(context, node)
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/parser.py", line 75, in _parse_nodes
    node_handlers[child_node_tag](context, child_node)
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/visual_studio/vcxproj/dependencies.py", line 289, in set_target_post_build_events
    'Post build'
  File "/home/user/.local/lib/python3.5/site-packages/cmake_converter/visual_studio/vcxproj/dependencies.py", line 256, in __set_target_build_events
    for build_event in command.text.split('\n'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by pavelliavonau** [comment]
@zowers , what kind of Command node do you have there?
