### ISSUE TITLE
AttributeError when convert project .vcxproj

### ISSUE THREAD

**Issue by RafaelGSS** [algorys/cmakeconverter#60]
Helllo everyone.

I have a problem when trying convert my project .vcxproj to CMake.

The project structure is:

```
- project/
      - project.sln
      - project.win/
         -  bin/
          - libs/
          - main.cpp
          - project.linux.vcxproj
          - project.linux.vcxproj.user
          - project.win.vcxproj
          - project.win.vcxproj.user
          - obj/
          - src/
```
I need convert the *project.linux.vcxproj* to CMake and when try:

```
 /c/repos/nptunnel.bridge.v2 (master)
$ cmake-converter -p project.win/project.linux.vcxproj
```

I have follow:

```
INFO : Project to convert = project.win/project.linux.vcxproj
WARN : CMakeLists.txt path is not set. He will be generated in current directory.
INFO : CMakeLists will be build in current directory.
WARN : No Output Debug define. Use [Debug/bin] by default !
WARN : No Output Release define. Use [Release/bin] by default !
INFO : C++ Extensions found: ['cpp']
INFO : Include Directories is not set.
INFO : No link needed.
OK   : Warning : TurnOffAllWarnings
INFO : No WholeProgramOptimization for Debug
INFO : No WholeProgramOptimization for Release
INFO : No UseDebugLibrairies for Debug
INFO : No UseDebugLibrairies for Release
INFO : No RuntimeLibrary for Debug
INFO : No RuntimeLibrary for Release
INFO : No Optimization for Debug
INFO : No Optimization for Release
INFO : No IntrinsicFunctions for Debug
INFO : No IntrinsicFunctions for Release
INFO : No RuntimeTypeInfo for Debug
INFO : No RuntimeTypeInfo for Release
INFO : No FunctionLevelLinking for release.
INFO : No GenerateDebugInformation for debug.
INFO : No GenerateDebugInformation for release.
OK   : ExceptionHandling for debug.
OK   : ExceptionHandling for release.
OK   : Debug   FLAGS found =  /Ws /EHsc
OK   : Release FLAGS found =  /Ws /EHsc
INFO : No C++ std version specified. CMake will use "c++11" by default.
Traceback (most recent call last):
  File "C:\Users\rafae\AppData\Local\Programs\Python\Python37-32\Scripts\cmake-converter-script.py", line 11, in <module>
    load_entry_point('cmake-converter==1.1.0', 'console_scripts', 'cmake-converter')()
  File "c:\users\rafae\appdata\local\programs\python\python37-32\lib\site-packages\cmake_converter\main.py", line 113, in main
    data_converter.create_data()
  File "c:\users\rafae\appdata\local\programs\python\python37-32\lib\site-packages\cmake_converter\data_converter.py", line 122, in create_data
    files.add_target_artefact()
  File "c:\users\rafae\appdata\local\programs\python\python37-32\lib\site-packages\cmake_converter\project_files.py", line 142, in add_target_artefact
    if configurationtype.text == 'DynamicLibrary':
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by pavelliavonau** [comment]
@RafaelGSS, you are using obsolete version from pypi. Try new code from develop. 
Also -p option might not work correctly, use -s instead.

**Comment by RafaelGSS** [comment]
Ok, works fine. Thanks!
