### ISSUE TITLE
Quick command expecting variables.

### ISSUE THREAD

**Issue by TimJSwan89** [algorys/cmakeconverter#7]
I am attempting to convert the [ZFSin](https://github.com/lundman/ZFSin/commit/bca538faf3b80da38ed7ca91df3cd1039bbe3d9f) project into a cmake project and ran into this issue:
```
timothy@timothy-RVMatch-VirtualBox:~/Desktop/ZFSin-master/ZFSin$ cmake-converter -p ./ZFSin.vcxproj
INFO : Project to convert = ./ZFSin.vcxproj
WARN : CMakeLists.txt path is not set. He will be generated in current directory.
INFO : CMakeLists will be build in current directory.
Traceback (most recent call last):
  File "/usr/local/bin/cmake-converter", line 9, in <module>
    load_entry_point('cmake-converter==0.0.1', 'console_scripts', 'cmake-converter')()
  File "/usr/local/lib/python3.5/dist-packages/cmake_converter/main.py", line 104, in main
    all_data.create_data()
  File "/usr/local/lib/python3.5/dist-packages/cmake_converter/data_converter.py", line 88, in create_data
    variables.add_project_variables()
  File "/usr/local/lib/python3.5/dist-packages/cmake_converter/project_variables.py", line 98, in add_project_variables
    )[0]
IndexError: list index out of range
```

**Comment by algorys** [comment]
@TimJSwan89 ok, I'll have a look ASAP.

**Comment by algorys** [comment]
Please try last version, it should work now :wink:

**Comment by TimJSwan89** [comment]
Thanks.
Not sure if you want me to open another issue or not, but I am having trouble again. It appears that an expected file is not being generated.
```
timothy@timothy-VirtualBox:~/Desktop/ZFSin-master/ZFSin$ cmake-converter -p ./ZFSin.vcxproj
INFO : Project to convert = ./ZFSin.vcxproj
WARN : CMakeLists.txt path is not set. He will be generated in current directory.
INFO : CMakeLists will be build in current directory.
WARN : No Output Debug define. Use [Debug/bin] by default !
WARN : No Output Release define. Use [Release/bin] by default !
INFO : Include Directories is not set.
INFO : No link needed.
OK   : Warning : Level3
INFO : No WholeProgramOptimization for Debug
INFO : No WholeProgramOptimization for Release
OK   : UseDebugLibrairies for Debug
INFO : No RuntimeLibrary for Debug
INFO : No RuntimeLibrary for Release
INFO : No Optimization for Debug
INFO : No Optimization for Release
INFO : No IntrinsicFunctions for Debug
INFO : No IntrinsicFunctions for Release
INFO : No RuntimeTypeInfo for Debug
INFO : No RuntimeTypeInfo for Release
INFO : No FunctionLevelLinking for release.
INFO : No GenerateDebugInformation for debug.
INFO : No GenerateDebugInformation for release.
OK   : ExceptionHandling for debug.
OK   : ExceptionHandling for release.
OK   : Debug   FLAGS found =  /W3 /MD /EHsc
OK   : Release FLAGS found =  /W3 /EHsc
INFO : CMake will build an EXECUTABLE.
OK   : Additional Dependencies = wdmsec.lib;
```
That worked, so I run cmake:
```
timothy@timothy-VirtualBox:~/Desktop/ZFSin-master/ZFSin$ cmake .
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: Use Release by default.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/timothy/Desktop/ZFSin-master/ZFSin
```
Missing file realized during make:
```
timothy@timothy-VirtualBox:~/Desktop/ZFSin-master/ZFSin$ make
Scanning dependencies of target ZFSin
[  0%] Building C object CMakeFiles/ZFSin.dir/driver.c.o
/home/timothy/Desktop/ZFSin-master/ZFSin/driver.c:1:19: fatal error: ntddk.h: No such file or directory
compilation terminated.
CMakeFiles/ZFSin.dir/build.make:62: recipe for target 'CMakeFiles/ZFSin.dir/driver.c.o' failed
make[2]: *** [CMakeFiles/ZFSin.dir/driver.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ZFSin.dir/all' failed
make[1]: *** [CMakeFiles/ZFSin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by algorys** [comment]
Yes. I've same error on my side. But i can't find any file in your solution called `ntddk.h`. So maybe you've include somewhere this file but not in project.

It seems this file is specific to Windows also.

**Comment by algorys** [comment]
@TimJSwan89 did you have time to test?
