### ISSUE TITLE
getting actual filesystem name failed

### ISSUE THREAD

**Issue by martin-s** [algorys/cmakeconverter#72]
When include definition in a visual studio project file contains a variable (e.g. QTDIR), converter returns an error.
Remark: It doesn't matter whether includes are set or not. The develop branch is not working in current state.

>cmake-converter -p ConsoleApplication2.vcxproj
0.000000 processes count = 8
0.015614 warnings level = 3
0.015614 Conversion started: Project ConsoleApplication2
0.015614 WARN : ('Debug', 'Win32') : file or path "X:\ConsoleApplication2\ConsoleApplication2\$(QTDIR)\include" not found.
0.015614 WARN : ('Debug', 'Win32') : getting actual filesystem name failed : "X:\ConsoleApplication2\ConsoleApplication2\$(QTDIR)\include"
Traceback (most recent call last):
  File "D:\WPy-3710\python-3.7.1.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\WPy-3710\python-3.7.1.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\WPy-3710\python-3.7.1.amd64\Scripts\cmake-converter.exe\__main__.py", line 9, in <module>
  File "D:\WPy-3710\python-3.7.1.amd64\lib\site-packages\cmake_converter\main.py", line 150, in main
    convert_project(initial_context, project_abs_path, cmake_lists_path)
  File "D:\WPy-3710\python-3.7.1.amd64\lib\site-packages\cmake_converter\visual_studio\solution.py", line 209, in convert_project
    data_converter.convert(context)
  File "D:\WPy-3710\python-3.7.1.amd64\lib\site-packages\cmake_converter\data_converter.py", line 134, in convert
    self.write_data(context, cmake_file)
  File "D:\WPy-3710\python-3.7.1.amd64\lib\site-packages\cmake_converter\data_converter.py", line 97, in write_data
    context.variables.write_target_outputs(context, cmake_file)
  File "D:\WPy-3710\python-3.7.1.amd64\lib\site-packages\cmake_converter\project_variables.py", line 124, in write_target_outputs
    default='${PROJECT_NAME}'
  File "D:\WPy-3710\python-3.7.1.amd64\lib\site-packages\cmake_converter\utils.py", line 298, in write_property_of_settings
    in_quotes
  File "D:\WPy-3710\python-3.7.1.amd64\lib\site-packages\cmake_converter\utils.py", line 206, in write_selected_sln_setting
    mapped_setting = settings[sln_setting_2_project_setting[sln_setting]]
KeyError: (None, None)

**Comment by pavelliavonau** [comment]
What about -s option?

**Comment by pavelliavonau** [comment]
cc34f2b
try this revision

**Comment by martin-s** [comment]
You're right. The -p option is not really supported. The solution entry should be working and show better results.
